// One-time, idempotent vault migration: flat notes -> memory/ zone, plus the
// shared document tree and the vault's own map. Safe to run twice.
import { readdirSync, readFileSync, existsSync, mkdirSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { vaultDir, writeIndex } from '../src/lib/akira/memory/store';
import { isNoteFile } from '../src/lib/akira/memory/note';

export const ZONES = ['memory', 'projects', 'ops', 'research', 'outputs', 'personal'] as const;

const ROOT_KEEP = new Set(['SOUL.md', 'SOUL.proposed.md', 'CLAUDE.md', 'INDEX.md']);

const ZONE_BLURB: Record<string, string> = {
  memory: "AKIRA's own notes. Written only through the remember/forget tools. Do not hand-edit.",
  projects: 'Per-project knowledge, one folder per projects.id. Title lives in each folder INDEX.md.',
  ops: 'Runbooks, machine topology, the backup chain, incident write-ups.',
  research: 'Raw captures distilled into durable pages.',
  outputs: 'Specs, plans, and reports worth finding again.',
  personal: 'Goals, journals, reviews.',
};

const CLAUDE_MD = `# AKIRA's vault

The directory is named \`akira-memory\` for historical reasons — it holds the whole
knowledge base now, not only her memory.

## Zones

${ZONES.map((z) => `- \`${z}/\` — ${ZONE_BLURB[z]}`).join('\n')}

## Navigation pattern

Read the \`INDEX.md\` at each level before globbing. Every folder's INDEX.md lists
what is in it, one line per entry, with a summary worth reading. Descend only
into the folder the index points at.

## Conventions

- \`memory/INDEX.md\` is generated by the code. Never hand-edit it.
- Every other \`INDEX.md\` is maintained by AKIRA. When you add a document to a
  folder, add its line to that folder's INDEX.md in the same turn.
- Link related pages with \`[[slug]]\`. Slugs are unique filenames, so links work
  regardless of folder depth.
- One fact per note in \`memory/\`. Documents elsewhere may be any length.
`;

const ROOT_INDEX = `# Vault map

${ZONES.map((z) => `- [[${z}]] — ${ZONE_BLURB[z]}`).join('\n')}

See CLAUDE.md for the navigation pattern.
`;

export function migrateVault(dir: string = vaultDir()): { moved: number; created: string[] } {
  // Pre-migration, the flat vault's root INDEX.md IS the generated recall
  // index — safe (in fact required) to replace on the very first run. Once
  // migrated, memory/ exists and the root INDEX.md is the operator-editable
  // zone map, which must never be clobbered again. Use memory/'s existence,
  // captured before we create it below, to tell the two situations apart.
  const alreadyMigrated = existsSync(join(dir, 'memory'));

  const created: string[] = [];
  for (const z of ZONES) {
    const p = join(dir, z);
    if (!existsSync(p)) {
      mkdirSync(p, { recursive: true });
      created.push(z);
    }
  }

  let moved = 0;
  for (const f of readdirSync(dir)) {
    if (!f.endsWith('.md') || ROOT_KEEP.has(f)) continue;
    const src = join(dir, f);
    let md = '';
    try {
      md = readFileSync(src, 'utf8');
    } catch {
      continue; // a directory entry ending in .md, or unreadable — leave it alone
    }
    if (!isNoteFile(md)) continue; // stray file, not a memory note
    const dest = join(dir, 'memory', f);
    if (existsSync(dest)) continue; // name collision with an existing memory note — never overwrite, leave at root for a human to resolve
    renameSync(src, dest);
    moved++;
  }

  // CLAUDE.md is new territory — the flat vault never had one — so "write
  // only when missing" is enough to protect operator edits on every re-run.
  if (!existsSync(join(dir, 'CLAUDE.md'))) writeFileSync(join(dir, 'CLAUDE.md'), CLAUDE_MD);

  // INDEX.md is trickier: pre-migration it's the stale flat-vault recall
  // index and must be replaced; post-migration it's the operator-editable
  // zone map and must never be clobbered again.
  if (!alreadyMigrated || !existsSync(join(dir, 'INDEX.md'))) {
    writeFileSync(join(dir, 'INDEX.md'), ROOT_INDEX);
  }
  for (const z of ZONES) {
    if (z === 'memory') continue; // generated below
    const p = join(dir, z, 'INDEX.md');
    if (!existsSync(p)) writeFileSync(p, `# ${z}\n\n${ZONE_BLURB[z]}\n\n(empty)\n`);
  }
  writeIndex(join(dir, 'memory'));

  return { moved, created };
}

// CLI entry: `pnpm vault:migrate`
if (process.argv[1]?.endsWith('migrate-vault.ts')) {
  const dir = vaultDir();
  if (!existsSync(dir)) {
    console.error(`No vault at ${dir}`);
    process.exit(1);
  }
  const { moved, created } = migrateVault(dir);
  console.log(`Vault migrated at ${dir}: ${moved} notes moved, zones created: ${created.join(', ') || 'none'}`);
}
